# Generated by Django 4.1.13 on 2024-05-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobs",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="professional",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="school",
            options={"managed": False},
        ),
    ]
