# 邮箱配置
EMAIL_ADDRESS:
EMAIL_USE_TLS: False
EMAIL_USE_SSL: True
EMAIL_HOST: smtp.qq.com
EMAIL_PORT: 465
EMAIL_HOST_USER:
EMAIL_HOST_PASSWORD:

# 数据库链接信息
DB_NAME: maxkb
DB_HOST: 192.168.3.86
DB_PORT: 5432
DB_USER: postgres
DB_PASSWORD: Admin_1234
DB_ENGINE: django.db.backends.postgresql_psycopg2
EMBEDDING_MODEL_PATH: /Users/lei/python/MaxKB/apps/model/embedding
EMBEDDING_MODEL_NAME: /Users/lei/python/MaxKB/apps/model/embedding/shibing624_text2vec-base-chinese

DEBUG: false

TIME_ZONE: Asia/Shanghai
# # 邮箱配置
# EMAIL_ADDRESS:
# EMAIL_USE_TLS: False
# EMAIL_USE_SSL: True
# EMAIL_HOST: smtp.qq.com
# EMAIL_PORT: 465
# EMAIL_HOST_USER:
# EMAIL_HOST_PASSWORD:

# # 数据库链接信息
# DB_NAME: maxkb
# DB_HOST: localhost
# DB_PORT: 5432
# DB_USER: root
# DB_PASSWORD: xxxxxxx
# DB_ENGINE: django.db.backends.postgresql_psycopg2

# DEBUG: false

# TIME_ZONE: Asia/Shanghai
