# # 邮箱配置
# EMAIL_ADDRESS: ${EMAIL_ADDRESS}
# EMAIL_USE_TLS: ${EMAIL_USE_TLS}
# EMAIL_USE_SSL: ${EMAIL_USE_SSL}
# EMAIL_HOST: ${EMAIL_HOST}
# EMAIL_PORT: ${EMAIL_PORT}
# EMAIL_HOST_USER: ${EMAIL_HOST_USER}
# EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}

# 数据库链接信息
DB_NAME: education-dev
DB_HOST: 192.168.3.86
DB_PORT: 5432
DB_USER: postgres
DB_PASSWORD: Admin_1234
DB_ENGINE: django.db.backends.postgresql_psycopg2
EMBEDDING_MODEL_PATH: /usr/local/share/model/embedding
EMBEDDING_MODEL_NAME: /usr/local/share/model/embedding/shibing624_text2vec-base-chinese

DEBUG: false

TIME_ZONE: Asia/Shanghai
